// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



package org.usfirst.frc2811.Stronghold2016.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class AutonomousCrossRockWall extends CommandGroup {

    public AutonomousCrossRockWall() {
    	//This should be helpful! 
    	// Selecting autonomous modes via Smart Dashboard
    	// https://wpilib.screenstepslive.com/s/4485/m/26401/l/255419-choosing-an-autonomous-program-from-smartdashboard
    	
    		
    		/*
    	// 	Group A: Porticulis = 1, Cheval de Frise = 2
    	// 	Group B: Ramparts = 3, Moat = 4
    	// 	Group C: Drawbridge = 5, Sally Port = 6
    	// 	Group D: Rock Wall = 7, Rough Terrain = 8
    	// 	Low Bar = 9
    	// 	Positions: [1][2][3][4][5]
    	*/
    	//rock wall wants low gear and 3.5 seconds
    	//moat wants high gear  100% speed and 5 seconds
    	
    	addSequential(new ShiftGearsLow());
    	addSequential(new IntakeHoming());
    	addSequential(new Wait(10));
    	addSequential(new SketchyDrive(1,2));    	
    	addSequential(new IntakeHoming()); 
    }

   
}
