// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.Stronghold2016.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousCommand extends CommandGroup {

    public AutonomousCommand(int defense, int goal) {
    	
    	/*
    	// 	Group A: Porticulis = 1, Cheval de Frise = 2
    	// 	Group B: Ramparts = 3, Moat = 4
    	// 	Group C: Drawbridge = 5, Sally Port = 6
    	// 	Group D: Rock Wall = 7, Rough Terrain = 8
    	// 	Low Bar = 9
    	// 	Positions: [1][2][3][4][5]
    	*/
    	   	addSequential(new IntakeHoming()); 

   	 //addSequential(new IntakeLifterAngle(0),2);   	
	 //addSequential(new IntakeLifterAngle(90)); 
	// addSequential(new SketchyDrive(),2);
	 //addSequential(new IntakeLifterAngle(10),2);   	
	 //addSequential(new IntakeLifterAngle(0),2);   	
	 //addSequential(new IntakeLifterAngle(-10),2);
	 
	 
    	//addSequential(new BreachDefenses(defense));
       	//addSequential(new ResetAlignment(goal));
    	//addSequential(new ShootBall());
    	
    }

   
}
