// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.Stronghold2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2811.Stronghold2016.Robot;

/**
 *
 */
public class SetAngle extends Command {

	private double angle;
	
    public SetAngle(double degrees) {
    	angle=degrees;
    }

    // Called just before this Command runs the first time
    public void initialize() {
    	//Robot.chassis.resetPID();    	    	
    }

    // Called repeatedly when this Command is scheduled to run
    public void execute() {
    	//Robot.chassis.setRotation(angle);
    }

    // Make this return true when this Command no longer needs to run execute()
    public boolean isFinished() {
    	System.out.println("Attempting to determine if robot should stop");
        //return Robot.chassis.isOnTarget();//||!Robot.oi.button4.get();
    	return true;
    	//return false;
    }

    // Called once after isFinished returns true
    public void end() {
    	//Robot.chassis.resetPID();
    	//Robot.chassis.setOperatorControl();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
     public void interrupted() {
    	end();
    }
}
