// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2811.Stronghold2016.subsystems;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Intake extends Subsystem {

	private static SpeedController intakeMotor1 = new Talon(4);
    private static SpeedController intakeMotor2 = new Talon(5);
    private static Solenoid intakeSolenoid = new Solenoid(0, 1);

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    	intakeSolenoid.set(false);
    	intakeMotor2.setInverted(true);
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void intakeSet(double speed){
    	intakeMotor1.set(speed);
    	intakeMotor2.set(speed);
    }
    
    public void intakeToggle(){
    	intakeSolenoid.set(!intakeSolenoid.get());
    }
    
}

