package org.usfirst.frc2811.Stronghold2016.subsystems;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.hal.CanTalonJNI;



import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class IntakeLifter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private CANTalon intakeLifterMotor = new CANTalon(7);
    private CANTalon intakeMotor = new CANTalon(6);
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
     * This is used to hold part of the PID
     */
    double iterm=0;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public IntakeLifter(){
    	intakeLifterMotor.reset();
    	intakeLifterMotor.clearStickyFaults();
    	intakeLifterMotor.reverseOutput(true);//This is correct on the practice robot
    	intakeLifterMotor.enableBrakeMode(false);//It keeps it from stalling when hitting the low bar
    	intakeLifterMotor.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Absolute);
    	intakeLifterPIDInit();
    	//Robot.smartDashboard.getNumber("p", 1);
    	//smartDashboard.getNumber("i", 0);
    	//smartDashboard.getNumber("d", 0);
    	
    	intakeMotor.reset();
    	intakeMotor.clearStickyFaults();
    	intakeMotor.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	intakeMotor.enable();
    	intakeMotor.set(0);

    }
    public void intakeLifterPIDInit(){
    	intakeLifterMotor.changeControlMode(CANTalon.TalonControlMode.Current);    	
    	intakeLifterMotor.setPID(.251, 0.00, 00); //works good for the arm prototype
    	intakeLifterMotor.setIZone(100);
    	intakeLifterMotor.enable();
    	resetEncoderPosition();
    	intakeLifterMotor.set(intakeLifterMotor.get());

    }
    
    public boolean intakeLifterHoming(){
    	intakeLifterMotor.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	intakeLifterMotor.enable();
    	//intakeLifterMotor.set(0.25); //goes up on practice bot
    	//intakeLifterMotor.set(0.25); //goes down on competition bot
    	intakeLifterMotor.set(-.15);
    	if(intakeLifterMotor.isFwdLimitSwitchClosed()){
    		intakeLifterPIDInit();
    		return true;
    	}
    	return false;
    }
    public void spinIntake(double speed){
    	intakeMotor.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	intakeMotor.enable();
    	intakeMotor.set(speed);
    }
    public void resetEncoderPosition(){
    	System.out.println("initial value"+	intakeLifterMotor.get());
    	intakeLifterMotor.setEncPosition(-1500);
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    //Part One checking direction of motor and correct limit switch
    public void setMotorVoltage(){
    	intakeLifterMotor.changeControlMode(CANTalon.TalonControlMode.PercentVbus);
    	intakeLifterMotor.enable();
    	intakeLifterMotor.set(0.25);
    	
    }
    
    public void setPosition(double position){
    	//double pgain=smartDashboard.getNumber("p");
    	double pgain=.004;
    	double igain=0.000001;
    	double error=(position-intakeLifterMotor.getEncPosition());
    	double p=pgain*error;
    	iterm=iterm+igain*error;
    	//cap iterm at 100
    	if(iterm>100)iterm=100; 
    	if(iterm<-100)iterm=-100; 
    	
    	double out=p+iterm;
    	intakeLifterMotor.enable();
    	//stop doing things with small error, hopefully avoid oscillations
    	//if(error<2 && error>-2)out=0;
    	
    	//cap output at 5 amps
    	if(out>5)out=5;
    	if(out<-5)out=-5;
    	
    	intakeLifterMotor.set(out);
    	
    	System.out.println("=================");
		System.out.println("Position: " +position);
		System.out.println("EncPos: " +intakeLifterMotor.getEncPosition());
		//System.out.println("Pos: " +intakeLifterMotor.getPosition());
		//System.out.println("error : " +intakeLifterMotor.getClosedLoopError());

	    Timer.delay(.05);
    }
    public void readStuff(){
    	System.out.println("=================");
		System.out.println("Setpoint: " +intakeLifterMotor.getSetpoint());
		System.out.println("EncPos: " +intakeLifterMotor.getEncPosition());
		System.out.println("Pos: " +intakeLifterMotor.getPosition());
		System.out.println("error : " +intakeLifterMotor.getClosedLoopError());
    }
}

